#include<iostream.h>
#include<conio.h>
#include<string.h>
class employee[5]
{
  public:
  char name[20],address[50],email[20],role[20];
  int id,salery,experience,contact;


};
void main()
{
	clrscr();
	employee e;


     cout<<"enter your name:";
     cin>>e.[5]name;
     cout<<"enter your id:";
     cin>>e.[5]id;
     cout<<"enter your role";
     cin>>e.[5]role;
     cout<<"enter your salary";
     cin>>e.[5]salery;
     cout<<"enter your eexperience:";
     cin>>e.[5]experience;
     cout<<"enter your address:";
     cin>>e.[5]address;
     cout<<"enter your email:";
     cin>>e.[5]email;
     cout<<"enter your contact number:";
     cin>>e.[5]contact;


     cout<<"your name is==>"<<e.[5]name<<endl;
     cout<<"your id is==>"<<e.[5]id<<endl;
     cout<<"your role is==>"<<e.[5]role<<endl;
     cout<<"your salary is==>"<<e.[5]salery<<endl;
     cout<<"your eexperience is==>"<<e.[5]experience<<endl;
     cout<<"your address is==>"<<e.[5]experience<<endl;
     cout<<"your email is==>"<<e.[5]email<<endl;
     cout<<"your contact number is==>"e.[5]contact;





	getch();
}